// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoMessage.proto

package com.apron.mobilesdk.state;

public final class ProtoMessage {
  private ProtoMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Message)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string requestId = 1;</code>
     * @return The requestId.
     */
    java.lang.String getRequestId();
    /**
     * <code>string requestId = 1;</code>
     * @return The bytes for requestId.
     */
    com.google.protobuf.ByteString
        getRequestIdBytes();

    /**
     * <code>string equipmentId = 2;</code>
     * @return The equipmentId.
     */
    java.lang.String getEquipmentId();
    /**
     * <code>string equipmentId = 2;</code>
     * @return The bytes for equipmentId.
     */
    com.google.protobuf.ByteString
        getEquipmentIdBytes();

    /**
     * <code>string method = 3;</code>
     * @return The method.
     */
    java.lang.String getMethod();
    /**
     * <code>string method = 3;</code>
     * @return The bytes for method.
     */
    com.google.protobuf.ByteString
        getMethodBytes();

    /**
     * <code>map&lt;string, string&gt; para = 4;</code>
     */
    int getParaCount();
    /**
     * <code>map&lt;string, string&gt; para = 4;</code>
     */
    boolean containsPara(
        java.lang.String key);
    /**
     * Use {@link #getParaMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getPara();
    /**
     * <code>map&lt;string, string&gt; para = 4;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getParaMap();
    /**
     * <code>map&lt;string, string&gt; para = 4;</code>
     */

    java.lang.String getParaOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; para = 4;</code>
     */

    java.lang.String getParaOrThrow(
        java.lang.String key);

    /**
     * <code>sint32 code = 5;</code>
     * @return The code.
     */
    int getCode();

    /**
     * <code>string result = 6;</code>
     * @return The result.
     */
    java.lang.String getResult();
    /**
     * <code>string result = 6;</code>
     * @return The bytes for result.
     */
    com.google.protobuf.ByteString
        getResultBytes();

    /**
     * <code>string requestTime = 7;</code>
     * @return The requestTime.
     */
    java.lang.String getRequestTime();
    /**
     * <code>string requestTime = 7;</code>
     * @return The bytes for requestTime.
     */
    com.google.protobuf.ByteString
        getRequestTimeBytes();

    /**
     * <code>string responseTime = 8;</code>
     * @return The responseTime.
     */
    java.lang.String getResponseTime();
    /**
     * <code>string responseTime = 8;</code>
     * @return The bytes for responseTime.
     */
    com.google.protobuf.ByteString
        getResponseTimeBytes();
  }
  /**
   * <pre>
   *这里是注释juanq
   * </pre>
   *
   * Protobuf type {@code Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageLite<
          Message, Message.Builder> implements
      // @@protoc_insertion_point(message_implements:Message)
      MessageOrBuilder {
    private Message() {
      requestId_ = "";
      equipmentId_ = "";
      method_ = "";
      result_ = "";
      requestTime_ = "";
      responseTime_ = "";
    }
    public static final int REQUESTID_FIELD_NUMBER = 1;
    private java.lang.String requestId_;
    /**
     * <code>string requestId = 1;</code>
     * @return The requestId.
     */
    @java.lang.Override
    public java.lang.String getRequestId() {
      return requestId_;
    }
    /**
     * <code>string requestId = 1;</code>
     * @return The bytes for requestId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(requestId_);
    }
    /**
     * <code>string requestId = 1;</code>
     * @param value The requestId to set.
     */
    private void setRequestId(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      requestId_ = value;
    }
    /**
     * <code>string requestId = 1;</code>
     */
    private void clearRequestId() {
      
      requestId_ = getDefaultInstance().getRequestId();
    }
    /**
     * <code>string requestId = 1;</code>
     * @param value The bytes for requestId to set.
     */
    private void setRequestIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      requestId_ = value.toStringUtf8();
      
    }

    public static final int EQUIPMENTID_FIELD_NUMBER = 2;
    private java.lang.String equipmentId_;
    /**
     * <code>string equipmentId = 2;</code>
     * @return The equipmentId.
     */
    @java.lang.Override
    public java.lang.String getEquipmentId() {
      return equipmentId_;
    }
    /**
     * <code>string equipmentId = 2;</code>
     * @return The bytes for equipmentId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEquipmentIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(equipmentId_);
    }
    /**
     * <code>string equipmentId = 2;</code>
     * @param value The equipmentId to set.
     */
    private void setEquipmentId(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      equipmentId_ = value;
    }
    /**
     * <code>string equipmentId = 2;</code>
     */
    private void clearEquipmentId() {
      
      equipmentId_ = getDefaultInstance().getEquipmentId();
    }
    /**
     * <code>string equipmentId = 2;</code>
     * @param value The bytes for equipmentId to set.
     */
    private void setEquipmentIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      equipmentId_ = value.toStringUtf8();
      
    }

    public static final int METHOD_FIELD_NUMBER = 3;
    private java.lang.String method_;
    /**
     * <code>string method = 3;</code>
     * @return The method.
     */
    @java.lang.Override
    public java.lang.String getMethod() {
      return method_;
    }
    /**
     * <code>string method = 3;</code>
     * @return The bytes for method.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMethodBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(method_);
    }
    /**
     * <code>string method = 3;</code>
     * @param value The method to set.
     */
    private void setMethod(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      method_ = value;
    }
    /**
     * <code>string method = 3;</code>
     */
    private void clearMethod() {
      
      method_ = getDefaultInstance().getMethod();
    }
    /**
     * <code>string method = 3;</code>
     * @param value The bytes for method to set.
     */
    private void setMethodBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      method_ = value.toStringUtf8();
      
    }

    public static final int PARA_FIELD_NUMBER = 4;
    private static final class ParaDefaultEntryHolder {
      static final com.google.protobuf.MapEntryLite<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntryLite
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapFieldLite<
        java.lang.String, java.lang.String> para_ =
            com.google.protobuf.MapFieldLite.emptyMapField();
    private com.google.protobuf.MapFieldLite<java.lang.String, java.lang.String>
    internalGetPara() {
      return para_;
    }
    private com.google.protobuf.MapFieldLite<java.lang.String, java.lang.String>
    internalGetMutablePara() {
      if (!para_.isMutable()) {
        para_ = para_.mutableCopy();
      }
      return para_;
    }
    @java.lang.Override

    public int getParaCount() {
      return internalGetPara().size();
    }
    /**
     * <code>map&lt;string, string&gt; para = 4;</code>
     */
    @java.lang.Override

    public boolean containsPara(
        java.lang.String key) {
      java.lang.Class<?> keyClass = key.getClass();
      return internalGetPara().containsKey(key);
    }
    /**
     * Use {@link #getParaMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getPara() {
      return getParaMap();
    }
    /**
     * <code>map&lt;string, string&gt; para = 4;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getParaMap() {
      return java.util.Collections.unmodifiableMap(
          internalGetPara());
    }
    /**
     * <code>map&lt;string, string&gt; para = 4;</code>
     */
    @java.lang.Override

    public java.lang.String getParaOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      java.lang.Class<?> keyClass = key.getClass();
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetPara();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; para = 4;</code>
     */
    @java.lang.Override

    public java.lang.String getParaOrThrow(
        java.lang.String key) {
      java.lang.Class<?> keyClass = key.getClass();
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetPara();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    /**
     * <code>map&lt;string, string&gt; para = 4;</code>
     */
    private java.util.Map<java.lang.String, java.lang.String>
    getMutableParaMap() {
      return internalGetMutablePara();
    }

    public static final int CODE_FIELD_NUMBER = 5;
    private int code_;
    /**
     * <code>sint32 code = 5;</code>
     * @return The code.
     */
    @java.lang.Override
    public int getCode() {
      return code_;
    }
    /**
     * <code>sint32 code = 5;</code>
     * @param value The code to set.
     */
    private void setCode(int value) {
      
      code_ = value;
    }
    /**
     * <code>sint32 code = 5;</code>
     */
    private void clearCode() {
      
      code_ = 0;
    }

    public static final int RESULT_FIELD_NUMBER = 6;
    private java.lang.String result_;
    /**
     * <code>string result = 6;</code>
     * @return The result.
     */
    @java.lang.Override
    public java.lang.String getResult() {
      return result_;
    }
    /**
     * <code>string result = 6;</code>
     * @return The bytes for result.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getResultBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(result_);
    }
    /**
     * <code>string result = 6;</code>
     * @param value The result to set.
     */
    private void setResult(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      result_ = value;
    }
    /**
     * <code>string result = 6;</code>
     */
    private void clearResult() {
      
      result_ = getDefaultInstance().getResult();
    }
    /**
     * <code>string result = 6;</code>
     * @param value The bytes for result to set.
     */
    private void setResultBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      result_ = value.toStringUtf8();
      
    }

    public static final int REQUESTTIME_FIELD_NUMBER = 7;
    private java.lang.String requestTime_;
    /**
     * <code>string requestTime = 7;</code>
     * @return The requestTime.
     */
    @java.lang.Override
    public java.lang.String getRequestTime() {
      return requestTime_;
    }
    /**
     * <code>string requestTime = 7;</code>
     * @return The bytes for requestTime.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRequestTimeBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(requestTime_);
    }
    /**
     * <code>string requestTime = 7;</code>
     * @param value The requestTime to set.
     */
    private void setRequestTime(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      requestTime_ = value;
    }
    /**
     * <code>string requestTime = 7;</code>
     */
    private void clearRequestTime() {
      
      requestTime_ = getDefaultInstance().getRequestTime();
    }
    /**
     * <code>string requestTime = 7;</code>
     * @param value The bytes for requestTime to set.
     */
    private void setRequestTimeBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      requestTime_ = value.toStringUtf8();
      
    }

    public static final int RESPONSETIME_FIELD_NUMBER = 8;
    private java.lang.String responseTime_;
    /**
     * <code>string responseTime = 8;</code>
     * @return The responseTime.
     */
    @java.lang.Override
    public java.lang.String getResponseTime() {
      return responseTime_;
    }
    /**
     * <code>string responseTime = 8;</code>
     * @return The bytes for responseTime.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getResponseTimeBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(responseTime_);
    }
    /**
     * <code>string responseTime = 8;</code>
     * @param value The responseTime to set.
     */
    private void setResponseTime(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      responseTime_ = value;
    }
    /**
     * <code>string responseTime = 8;</code>
     */
    private void clearResponseTime() {
      
      responseTime_ = getDefaultInstance().getResponseTime();
    }
    /**
     * <code>string responseTime = 8;</code>
     * @param value The bytes for responseTime to set.
     */
    private void setResponseTimeBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      responseTime_ = value.toStringUtf8();
      
    }

    public static com.apron.mobilesdk.state.ProtoMessage.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.apron.mobilesdk.state.ProtoMessage.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.apron.mobilesdk.state.ProtoMessage.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.apron.mobilesdk.state.ProtoMessage.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.apron.mobilesdk.state.ProtoMessage.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.apron.mobilesdk.state.ProtoMessage.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.apron.mobilesdk.state.ProtoMessage.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.apron.mobilesdk.state.ProtoMessage.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.apron.mobilesdk.state.ProtoMessage.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.apron.mobilesdk.state.ProtoMessage.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.apron.mobilesdk.state.ProtoMessage.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.apron.mobilesdk.state.ProtoMessage.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.apron.mobilesdk.state.ProtoMessage.Message prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     *这里是注释juanq
     * </pre>
     *
     * Protobuf type {@code Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.apron.mobilesdk.state.ProtoMessage.Message, Builder> implements
        // @@protoc_insertion_point(builder_implements:Message)
        com.apron.mobilesdk.state.ProtoMessage.MessageOrBuilder {
      // Construct using com.apron.mobilesdk.state.ProtoMessage.Message.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string requestId = 1;</code>
       * @return The requestId.
       */
      @java.lang.Override
      public java.lang.String getRequestId() {
        return instance.getRequestId();
      }
      /**
       * <code>string requestId = 1;</code>
       * @return The bytes for requestId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getRequestIdBytes() {
        return instance.getRequestIdBytes();
      }
      /**
       * <code>string requestId = 1;</code>
       * @param value The requestId to set.
       * @return This builder for chaining.
       */
      public Builder setRequestId(
          java.lang.String value) {
        copyOnWrite();
        instance.setRequestId(value);
        return this;
      }
      /**
       * <code>string requestId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestId() {
        copyOnWrite();
        instance.clearRequestId();
        return this;
      }
      /**
       * <code>string requestId = 1;</code>
       * @param value The bytes for requestId to set.
       * @return This builder for chaining.
       */
      public Builder setRequestIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setRequestIdBytes(value);
        return this;
      }

      /**
       * <code>string equipmentId = 2;</code>
       * @return The equipmentId.
       */
      @java.lang.Override
      public java.lang.String getEquipmentId() {
        return instance.getEquipmentId();
      }
      /**
       * <code>string equipmentId = 2;</code>
       * @return The bytes for equipmentId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getEquipmentIdBytes() {
        return instance.getEquipmentIdBytes();
      }
      /**
       * <code>string equipmentId = 2;</code>
       * @param value The equipmentId to set.
       * @return This builder for chaining.
       */
      public Builder setEquipmentId(
          java.lang.String value) {
        copyOnWrite();
        instance.setEquipmentId(value);
        return this;
      }
      /**
       * <code>string equipmentId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearEquipmentId() {
        copyOnWrite();
        instance.clearEquipmentId();
        return this;
      }
      /**
       * <code>string equipmentId = 2;</code>
       * @param value The bytes for equipmentId to set.
       * @return This builder for chaining.
       */
      public Builder setEquipmentIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setEquipmentIdBytes(value);
        return this;
      }

      /**
       * <code>string method = 3;</code>
       * @return The method.
       */
      @java.lang.Override
      public java.lang.String getMethod() {
        return instance.getMethod();
      }
      /**
       * <code>string method = 3;</code>
       * @return The bytes for method.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getMethodBytes() {
        return instance.getMethodBytes();
      }
      /**
       * <code>string method = 3;</code>
       * @param value The method to set.
       * @return This builder for chaining.
       */
      public Builder setMethod(
          java.lang.String value) {
        copyOnWrite();
        instance.setMethod(value);
        return this;
      }
      /**
       * <code>string method = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMethod() {
        copyOnWrite();
        instance.clearMethod();
        return this;
      }
      /**
       * <code>string method = 3;</code>
       * @param value The bytes for method to set.
       * @return This builder for chaining.
       */
      public Builder setMethodBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMethodBytes(value);
        return this;
      }

      @java.lang.Override

      public int getParaCount() {
        return instance.getParaMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; para = 4;</code>
       */
      @java.lang.Override

      public boolean containsPara(
          java.lang.String key) {
        java.lang.Class<?> keyClass = key.getClass();
        return instance.getParaMap().containsKey(key);
      }

      public Builder clearPara() {
        copyOnWrite();
        instance.getMutableParaMap().clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; para = 4;</code>
       */

      public Builder removePara(
          java.lang.String key) {
        java.lang.Class<?> keyClass = key.getClass();
        copyOnWrite();
        instance.getMutableParaMap().remove(key);
        return this;
      }
      /**
       * Use {@link #getParaMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getPara() {
        return getParaMap();
      }
      /**
       * <code>map&lt;string, string&gt; para = 4;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, java.lang.String> getParaMap() {
        return java.util.Collections.unmodifiableMap(
            instance.getParaMap());
      }
      /**
       * <code>map&lt;string, string&gt; para = 4;</code>
       */
      @java.lang.Override

      public java.lang.String getParaOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        java.lang.Class<?> keyClass = key.getClass();
        java.util.Map<java.lang.String, java.lang.String> map =
            instance.getParaMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; para = 4;</code>
       */
      @java.lang.Override

      public java.lang.String getParaOrThrow(
          java.lang.String key) {
        java.lang.Class<?> keyClass = key.getClass();
        java.util.Map<java.lang.String, java.lang.String> map =
            instance.getParaMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      /**
       * <code>map&lt;string, string&gt; para = 4;</code>
       */
      public Builder putPara(
          java.lang.String key,
          java.lang.String value) {
        java.lang.Class<?> keyClass = key.getClass();
        java.lang.Class<?> valueClass = value.getClass();
        copyOnWrite();
        instance.getMutableParaMap().put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; para = 4;</code>
       */
      public Builder putAllPara(
          java.util.Map<java.lang.String, java.lang.String> values) {
        copyOnWrite();
        instance.getMutableParaMap().putAll(values);
        return this;
      }

      /**
       * <code>sint32 code = 5;</code>
       * @return The code.
       */
      @java.lang.Override
      public int getCode() {
        return instance.getCode();
      }
      /**
       * <code>sint32 code = 5;</code>
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(int value) {
        copyOnWrite();
        instance.setCode(value);
        return this;
      }
      /**
       * <code>sint32 code = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        copyOnWrite();
        instance.clearCode();
        return this;
      }

      /**
       * <code>string result = 6;</code>
       * @return The result.
       */
      @java.lang.Override
      public java.lang.String getResult() {
        return instance.getResult();
      }
      /**
       * <code>string result = 6;</code>
       * @return The bytes for result.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getResultBytes() {
        return instance.getResultBytes();
      }
      /**
       * <code>string result = 6;</code>
       * @param value The result to set.
       * @return This builder for chaining.
       */
      public Builder setResult(
          java.lang.String value) {
        copyOnWrite();
        instance.setResult(value);
        return this;
      }
      /**
       * <code>string result = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearResult() {
        copyOnWrite();
        instance.clearResult();
        return this;
      }
      /**
       * <code>string result = 6;</code>
       * @param value The bytes for result to set.
       * @return This builder for chaining.
       */
      public Builder setResultBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setResultBytes(value);
        return this;
      }

      /**
       * <code>string requestTime = 7;</code>
       * @return The requestTime.
       */
      @java.lang.Override
      public java.lang.String getRequestTime() {
        return instance.getRequestTime();
      }
      /**
       * <code>string requestTime = 7;</code>
       * @return The bytes for requestTime.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getRequestTimeBytes() {
        return instance.getRequestTimeBytes();
      }
      /**
       * <code>string requestTime = 7;</code>
       * @param value The requestTime to set.
       * @return This builder for chaining.
       */
      public Builder setRequestTime(
          java.lang.String value) {
        copyOnWrite();
        instance.setRequestTime(value);
        return this;
      }
      /**
       * <code>string requestTime = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestTime() {
        copyOnWrite();
        instance.clearRequestTime();
        return this;
      }
      /**
       * <code>string requestTime = 7;</code>
       * @param value The bytes for requestTime to set.
       * @return This builder for chaining.
       */
      public Builder setRequestTimeBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setRequestTimeBytes(value);
        return this;
      }

      /**
       * <code>string responseTime = 8;</code>
       * @return The responseTime.
       */
      @java.lang.Override
      public java.lang.String getResponseTime() {
        return instance.getResponseTime();
      }
      /**
       * <code>string responseTime = 8;</code>
       * @return The bytes for responseTime.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getResponseTimeBytes() {
        return instance.getResponseTimeBytes();
      }
      /**
       * <code>string responseTime = 8;</code>
       * @param value The responseTime to set.
       * @return This builder for chaining.
       */
      public Builder setResponseTime(
          java.lang.String value) {
        copyOnWrite();
        instance.setResponseTime(value);
        return this;
      }
      /**
       * <code>string responseTime = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearResponseTime() {
        copyOnWrite();
        instance.clearResponseTime();
        return this;
      }
      /**
       * <code>string responseTime = 8;</code>
       * @param value The bytes for responseTime to set.
       * @return This builder for chaining.
       */
      public Builder setResponseTimeBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setResponseTimeBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Message)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.apron.mobilesdk.state.ProtoMessage.Message();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "requestId_",
              "equipmentId_",
              "method_",
              "para_",
              ParaDefaultEntryHolder.defaultEntry,
              "code_",
              "result_",
              "requestTime_",
              "responseTime_",
            };
            java.lang.String info =
                "\u0000\b\u0000\u0000\u0001\b\b\u0001\u0000\u0000\u0001\u0208\u0002\u0208\u0003\u0208" +
                "\u00042\u0005\u000f\u0006\u0208\u0007\u0208\b\u0208";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.apron.mobilesdk.state.ProtoMessage.Message> parser = PARSER;
          if (parser == null) {
            synchronized (com.apron.mobilesdk.state.ProtoMessage.Message.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.apron.mobilesdk.state.ProtoMessage.Message>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:Message)
    private static final com.apron.mobilesdk.state.ProtoMessage.Message DEFAULT_INSTANCE;
    static {
      Message defaultInstance = new Message();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Message.class, defaultInstance);
    }

    public static com.apron.mobilesdk.state.ProtoMessage.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Message> PARSER;

    public static com.google.protobuf.Parser<Message> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
