// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RTKBaseStationList.proto

package com.apron.mobilesdk.state;

public final class ProtoBaseStationList {
  private ProtoBaseStationList() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface RTKBaseStationListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RTKBaseStationList)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string rtkBaseStationInformations = 1;</code>
     * @return The rtkBaseStationInformations.
     */
    java.lang.String getRtkBaseStationInformations();
    /**
     * <code>string rtkBaseStationInformations = 1;</code>
     * @return The bytes for rtkBaseStationInformations.
     */
    com.google.protobuf.ByteString
        getRtkBaseStationInformationsBytes();
  }
  /**
   * <pre>
   *返回搜索到的D-RTK基站列表
   * </pre>
   *
   * Protobuf type {@code RTKBaseStationList}
   */
  public  static final class RTKBaseStationList extends
      com.google.protobuf.GeneratedMessageLite<
          RTKBaseStationList, RTKBaseStationList.Builder> implements
      // @@protoc_insertion_point(message_implements:RTKBaseStationList)
      RTKBaseStationListOrBuilder {
    private RTKBaseStationList() {
      rtkBaseStationInformations_ = "";
    }
    public static final int RTKBASESTATIONINFORMATIONS_FIELD_NUMBER = 1;
    private java.lang.String rtkBaseStationInformations_;
    /**
     * <code>string rtkBaseStationInformations = 1;</code>
     * @return The rtkBaseStationInformations.
     */
    @java.lang.Override
    public java.lang.String getRtkBaseStationInformations() {
      return rtkBaseStationInformations_;
    }
    /**
     * <code>string rtkBaseStationInformations = 1;</code>
     * @return The bytes for rtkBaseStationInformations.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRtkBaseStationInformationsBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(rtkBaseStationInformations_);
    }
    /**
     * <code>string rtkBaseStationInformations = 1;</code>
     * @param value The rtkBaseStationInformations to set.
     */
    private void setRtkBaseStationInformations(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      rtkBaseStationInformations_ = value;
    }
    /**
     * <code>string rtkBaseStationInformations = 1;</code>
     */
    private void clearRtkBaseStationInformations() {
      
      rtkBaseStationInformations_ = getDefaultInstance().getRtkBaseStationInformations();
    }
    /**
     * <code>string rtkBaseStationInformations = 1;</code>
     * @param value The bytes for rtkBaseStationInformations to set.
     */
    private void setRtkBaseStationInformationsBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      rtkBaseStationInformations_ = value.toStringUtf8();
      
    }

    public static com.apron.mobilesdk.state.ProtoBaseStationList.RTKBaseStationList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.apron.mobilesdk.state.ProtoBaseStationList.RTKBaseStationList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.apron.mobilesdk.state.ProtoBaseStationList.RTKBaseStationList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.apron.mobilesdk.state.ProtoBaseStationList.RTKBaseStationList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.apron.mobilesdk.state.ProtoBaseStationList.RTKBaseStationList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.apron.mobilesdk.state.ProtoBaseStationList.RTKBaseStationList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.apron.mobilesdk.state.ProtoBaseStationList.RTKBaseStationList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.apron.mobilesdk.state.ProtoBaseStationList.RTKBaseStationList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.apron.mobilesdk.state.ProtoBaseStationList.RTKBaseStationList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.apron.mobilesdk.state.ProtoBaseStationList.RTKBaseStationList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.apron.mobilesdk.state.ProtoBaseStationList.RTKBaseStationList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.apron.mobilesdk.state.ProtoBaseStationList.RTKBaseStationList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.apron.mobilesdk.state.ProtoBaseStationList.RTKBaseStationList prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     *返回搜索到的D-RTK基站列表
     * </pre>
     *
     * Protobuf type {@code RTKBaseStationList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.apron.mobilesdk.state.ProtoBaseStationList.RTKBaseStationList, Builder> implements
        // @@protoc_insertion_point(builder_implements:RTKBaseStationList)
        com.apron.mobilesdk.state.ProtoBaseStationList.RTKBaseStationListOrBuilder {
      // Construct using com.apron.mobilesdk.state.ProtoBaseStationList.RTKBaseStationList.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string rtkBaseStationInformations = 1;</code>
       * @return The rtkBaseStationInformations.
       */
      @java.lang.Override
      public java.lang.String getRtkBaseStationInformations() {
        return instance.getRtkBaseStationInformations();
      }
      /**
       * <code>string rtkBaseStationInformations = 1;</code>
       * @return The bytes for rtkBaseStationInformations.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getRtkBaseStationInformationsBytes() {
        return instance.getRtkBaseStationInformationsBytes();
      }
      /**
       * <code>string rtkBaseStationInformations = 1;</code>
       * @param value The rtkBaseStationInformations to set.
       * @return This builder for chaining.
       */
      public Builder setRtkBaseStationInformations(
          java.lang.String value) {
        copyOnWrite();
        instance.setRtkBaseStationInformations(value);
        return this;
      }
      /**
       * <code>string rtkBaseStationInformations = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRtkBaseStationInformations() {
        copyOnWrite();
        instance.clearRtkBaseStationInformations();
        return this;
      }
      /**
       * <code>string rtkBaseStationInformations = 1;</code>
       * @param value The bytes for rtkBaseStationInformations to set.
       * @return This builder for chaining.
       */
      public Builder setRtkBaseStationInformationsBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setRtkBaseStationInformationsBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:RTKBaseStationList)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.apron.mobilesdk.state.ProtoBaseStationList.RTKBaseStationList();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "rtkBaseStationInformations_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0208";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.apron.mobilesdk.state.ProtoBaseStationList.RTKBaseStationList> parser = PARSER;
          if (parser == null) {
            synchronized (com.apron.mobilesdk.state.ProtoBaseStationList.RTKBaseStationList.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.apron.mobilesdk.state.ProtoBaseStationList.RTKBaseStationList>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:RTKBaseStationList)
    private static final com.apron.mobilesdk.state.ProtoBaseStationList.RTKBaseStationList DEFAULT_INSTANCE;
    static {
      RTKBaseStationList defaultInstance = new RTKBaseStationList();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        RTKBaseStationList.class, defaultInstance);
    }

    public static com.apron.mobilesdk.state.ProtoBaseStationList.RTKBaseStationList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<RTKBaseStationList> PARSER;

    public static com.google.protobuf.Parser<RTKBaseStationList> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
