// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DownlinkSignalQuality.proto

package com.apron.mobilesdk.state;

public final class ProtoDownlink {
  private ProtoDownlink() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface DownlinkOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Downlink)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *无线链路的信号质量百分比。(平台目前使用此参数作为图传信号质量)
     * </pre>
     *
     * <code>int32 quality = 1;</code>
     * @return The quality.
     */
    int getQuality();
  }
  /**
   * Protobuf type {@code Downlink}
   */
  public  static final class Downlink extends
      com.google.protobuf.GeneratedMessageLite<
          Downlink, Downlink.Builder> implements
      // @@protoc_insertion_point(message_implements:Downlink)
      DownlinkOrBuilder {
    private Downlink() {
    }
    public static final int QUALITY_FIELD_NUMBER = 1;
    private int quality_;
    /**
     * <pre>
     *无线链路的信号质量百分比。(平台目前使用此参数作为图传信号质量)
     * </pre>
     *
     * <code>int32 quality = 1;</code>
     * @return The quality.
     */
    @java.lang.Override
    public int getQuality() {
      return quality_;
    }
    /**
     * <pre>
     *无线链路的信号质量百分比。(平台目前使用此参数作为图传信号质量)
     * </pre>
     *
     * <code>int32 quality = 1;</code>
     * @param value The quality to set.
     */
    private void setQuality(int value) {
      
      quality_ = value;
    }
    /**
     * <pre>
     *无线链路的信号质量百分比。(平台目前使用此参数作为图传信号质量)
     * </pre>
     *
     * <code>int32 quality = 1;</code>
     */
    private void clearQuality() {
      
      quality_ = 0;
    }

    public static com.apron.mobilesdk.state.ProtoDownlink.Downlink parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.apron.mobilesdk.state.ProtoDownlink.Downlink parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.apron.mobilesdk.state.ProtoDownlink.Downlink parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.apron.mobilesdk.state.ProtoDownlink.Downlink parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.apron.mobilesdk.state.ProtoDownlink.Downlink parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.apron.mobilesdk.state.ProtoDownlink.Downlink parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.apron.mobilesdk.state.ProtoDownlink.Downlink parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.apron.mobilesdk.state.ProtoDownlink.Downlink parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.apron.mobilesdk.state.ProtoDownlink.Downlink parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.apron.mobilesdk.state.ProtoDownlink.Downlink parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.apron.mobilesdk.state.ProtoDownlink.Downlink parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.apron.mobilesdk.state.ProtoDownlink.Downlink parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.apron.mobilesdk.state.ProtoDownlink.Downlink prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code Downlink}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.apron.mobilesdk.state.ProtoDownlink.Downlink, Builder> implements
        // @@protoc_insertion_point(builder_implements:Downlink)
        com.apron.mobilesdk.state.ProtoDownlink.DownlinkOrBuilder {
      // Construct using com.apron.mobilesdk.state.ProtoDownlink.Downlink.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *无线链路的信号质量百分比。(平台目前使用此参数作为图传信号质量)
       * </pre>
       *
       * <code>int32 quality = 1;</code>
       * @return The quality.
       */
      @java.lang.Override
      public int getQuality() {
        return instance.getQuality();
      }
      /**
       * <pre>
       *无线链路的信号质量百分比。(平台目前使用此参数作为图传信号质量)
       * </pre>
       *
       * <code>int32 quality = 1;</code>
       * @param value The quality to set.
       * @return This builder for chaining.
       */
      public Builder setQuality(int value) {
        copyOnWrite();
        instance.setQuality(value);
        return this;
      }
      /**
       * <pre>
       *无线链路的信号质量百分比。(平台目前使用此参数作为图传信号质量)
       * </pre>
       *
       * <code>int32 quality = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearQuality() {
        copyOnWrite();
        instance.clearQuality();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Downlink)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.apron.mobilesdk.state.ProtoDownlink.Downlink();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "quality_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0004";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.apron.mobilesdk.state.ProtoDownlink.Downlink> parser = PARSER;
          if (parser == null) {
            synchronized (com.apron.mobilesdk.state.ProtoDownlink.Downlink.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.apron.mobilesdk.state.ProtoDownlink.Downlink>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:Downlink)
    private static final com.apron.mobilesdk.state.ProtoDownlink.Downlink DEFAULT_INSTANCE;
    static {
      Downlink defaultInstance = new Downlink();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Downlink.class, defaultInstance);
    }

    public static com.apron.mobilesdk.state.ProtoDownlink.Downlink getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Downlink> PARSER;

    public static com.google.protobuf.Parser<Downlink> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
