// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MissionExecutionEvent.proto

package com.apron.mobilesdk.state;

public final class ProtoMissionExecution {
  private ProtoMissionExecution() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface MissionExecutionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MissionExecution)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *飞机将执行的下一个任务的航路点索引。(平台取此值表示已过航点)
     * </pre>
     *
     * <code>int32 targetWaypointIndex = 1;</code>
     * @return The targetWaypointIndex.
     */
    int getTargetWaypointIndex();

    /**
     * <pre>
     *飞机当前航线的总航点数(航线开始-结束)
     * </pre>
     *
     * <code>int32 targetMissionWaypointSize = 3;</code>
     * @return The targetMissionWaypointSize.
     */
    int getTargetMissionWaypointSize();

    /**
     * <code>.MissionExecution.WaypointV2MissionExecuteState waypointV2MissionExecuteState = 2;</code>
     * @return The enum numeric value on the wire for waypointV2MissionExecuteState.
     */
    int getWaypointV2MissionExecuteStateValue();
    /**
     * <code>.MissionExecution.WaypointV2MissionExecuteState waypointV2MissionExecuteState = 2;</code>
     * @return The waypointV2MissionExecuteState.
     */
    com.apron.mobilesdk.state.ProtoMissionExecution.MissionExecution.WaypointV2MissionExecuteState getWaypointV2MissionExecuteState();
  }
  /**
   * Protobuf type {@code MissionExecution}
   */
  public  static final class MissionExecution extends
      com.google.protobuf.GeneratedMessageLite<
          MissionExecution, MissionExecution.Builder> implements
      // @@protoc_insertion_point(message_implements:MissionExecution)
      MissionExecutionOrBuilder {
    private MissionExecution() {
    }
    /**
     * <pre>
     *航线任务执行的状态
     * </pre>
     *
     * Protobuf enum {@code MissionExecution.WaypointV2MissionExecuteState}
     */
    public enum WaypointV2MissionExecuteState
        implements com.google.protobuf.Internal.EnumLite {
      /**
       * <pre>
       *航点任务正在初始化，这意味着任务已经开始。
       * </pre>
       *
       * <code>INITIALIZING = 0;</code>
       */
      INITIALIZING(0),
      /**
       * <pre>
       *飞机目前正前往第一个航路点。
       * </pre>
       *
       * <code>GO_TO_FIRST_WAYPOINT = 1;</code>
       */
      GO_TO_FIRST_WAYPOINT(1),
      /**
       * <pre>
       *飞机目前正在移动。
       * </pre>
       *
       * <code>MOVING = 2;</code>
       */
      MOVING(2),
      /**
       * <pre>
       * 飞机目前正在暂停。
       * </pre>
       *
       * <code>PAUSED = 3;</code>
       */
      PAUSED(3),
      /**
       * <pre>
       *飞机当前被用户中断。
       * </pre>
       *
       * <code>INTERRUPTED = 4;</code>
       */
      INTERRUPTED(4),
      /**
       * <pre>
       * 飞机完成航路点任务，从最后一个航路点起飞。
       * </pre>
       *
       * <code>FINISHED = 5;</code>
       */
      FINISHED(5),
      /**
       * <pre>
       *飞机已返回原点。当航线执行完成动作设置为GO_HOME时会发生这种情况。
       * </pre>
       *
       * <code>GO_HOME = 6;</code>
       */
      GO_HOME(6),
      /**
       * <pre>
       *飞机已降落。当航线执行完成动作设置为AUTO_LAND时会发生这种情况。
       * </pre>
       *
       * <code>LANDING = 7;</code>
       */
      LANDING(7),
      /**
       * <pre>
       *飞机已返回第一个航点。当航线执行完成动作设置为GO_FIRST_WAYPOINT时会发生这种情况。
       * </pre>
       *
       * <code>RETURN_TO_FIRST_WAYPOINT = 8;</code>
       */
      RETURN_TO_FIRST_WAYPOINT(8),
      /**
       * <pre>
       *未知
       * </pre>
       *
       * <code>UNKNOWN = 255;</code>
       */
      UNKNOWN(255),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       *航点任务正在初始化，这意味着任务已经开始。
       * </pre>
       *
       * <code>INITIALIZING = 0;</code>
       */
      public static final int INITIALIZING_VALUE = 0;
      /**
       * <pre>
       *飞机目前正前往第一个航路点。
       * </pre>
       *
       * <code>GO_TO_FIRST_WAYPOINT = 1;</code>
       */
      public static final int GO_TO_FIRST_WAYPOINT_VALUE = 1;
      /**
       * <pre>
       *飞机目前正在移动。
       * </pre>
       *
       * <code>MOVING = 2;</code>
       */
      public static final int MOVING_VALUE = 2;
      /**
       * <pre>
       * 飞机目前正在暂停。
       * </pre>
       *
       * <code>PAUSED = 3;</code>
       */
      public static final int PAUSED_VALUE = 3;
      /**
       * <pre>
       *飞机当前被用户中断。
       * </pre>
       *
       * <code>INTERRUPTED = 4;</code>
       */
      public static final int INTERRUPTED_VALUE = 4;
      /**
       * <pre>
       * 飞机完成航路点任务，从最后一个航路点起飞。
       * </pre>
       *
       * <code>FINISHED = 5;</code>
       */
      public static final int FINISHED_VALUE = 5;
      /**
       * <pre>
       *飞机已返回原点。当航线执行完成动作设置为GO_HOME时会发生这种情况。
       * </pre>
       *
       * <code>GO_HOME = 6;</code>
       */
      public static final int GO_HOME_VALUE = 6;
      /**
       * <pre>
       *飞机已降落。当航线执行完成动作设置为AUTO_LAND时会发生这种情况。
       * </pre>
       *
       * <code>LANDING = 7;</code>
       */
      public static final int LANDING_VALUE = 7;
      /**
       * <pre>
       *飞机已返回第一个航点。当航线执行完成动作设置为GO_FIRST_WAYPOINT时会发生这种情况。
       * </pre>
       *
       * <code>RETURN_TO_FIRST_WAYPOINT = 8;</code>
       */
      public static final int RETURN_TO_FIRST_WAYPOINT_VALUE = 8;
      /**
       * <pre>
       *未知
       * </pre>
       *
       * <code>UNKNOWN = 255;</code>
       */
      public static final int UNKNOWN_VALUE = 255;


      @java.lang.Override
      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static WaypointV2MissionExecuteState valueOf(int value) {
        return forNumber(value);
      }

      public static WaypointV2MissionExecuteState forNumber(int value) {
        switch (value) {
          case 0: return INITIALIZING;
          case 1: return GO_TO_FIRST_WAYPOINT;
          case 2: return MOVING;
          case 3: return PAUSED;
          case 4: return INTERRUPTED;
          case 5: return FINISHED;
          case 6: return GO_HOME;
          case 7: return LANDING;
          case 8: return RETURN_TO_FIRST_WAYPOINT;
          case 255: return UNKNOWN;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<WaypointV2MissionExecuteState>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          WaypointV2MissionExecuteState> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<WaypointV2MissionExecuteState>() {
              @java.lang.Override
              public WaypointV2MissionExecuteState findValueByNumber(int number) {
                return WaypointV2MissionExecuteState.forNumber(number);
              }
            };

      public static com.google.protobuf.Internal.EnumVerifier 
          internalGetVerifier() {
        return WaypointV2MissionExecuteStateVerifier.INSTANCE;
      }

      private static final class WaypointV2MissionExecuteStateVerifier implements 
           com.google.protobuf.Internal.EnumVerifier { 
              static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new WaypointV2MissionExecuteStateVerifier();
              @java.lang.Override
              public boolean isInRange(int number) {
                return WaypointV2MissionExecuteState.forNumber(number) != null;
              }
            };

      private final int value;

      private WaypointV2MissionExecuteState(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:MissionExecution.WaypointV2MissionExecuteState)
    }

    public static final int TARGETWAYPOINTINDEX_FIELD_NUMBER = 1;
    private int targetWaypointIndex_;
    /**
     * <pre>
     *飞机将执行的下一个任务的航路点索引。(平台取此值表示已过航点)
     * </pre>
     *
     * <code>int32 targetWaypointIndex = 1;</code>
     * @return The targetWaypointIndex.
     */
    @java.lang.Override
    public int getTargetWaypointIndex() {
      return targetWaypointIndex_;
    }
    /**
     * <pre>
     *飞机将执行的下一个任务的航路点索引。(平台取此值表示已过航点)
     * </pre>
     *
     * <code>int32 targetWaypointIndex = 1;</code>
     * @param value The targetWaypointIndex to set.
     */
    private void setTargetWaypointIndex(int value) {
      
      targetWaypointIndex_ = value;
    }
    /**
     * <pre>
     *飞机将执行的下一个任务的航路点索引。(平台取此值表示已过航点)
     * </pre>
     *
     * <code>int32 targetWaypointIndex = 1;</code>
     */
    private void clearTargetWaypointIndex() {
      
      targetWaypointIndex_ = 0;
    }

    public static final int TARGETMISSIONWAYPOINTSIZE_FIELD_NUMBER = 3;
    private int targetMissionWaypointSize_;
    /**
     * <pre>
     *飞机当前航线的总航点数(航线开始-结束)
     * </pre>
     *
     * <code>int32 targetMissionWaypointSize = 3;</code>
     * @return The targetMissionWaypointSize.
     */
    @java.lang.Override
    public int getTargetMissionWaypointSize() {
      return targetMissionWaypointSize_;
    }
    /**
     * <pre>
     *飞机当前航线的总航点数(航线开始-结束)
     * </pre>
     *
     * <code>int32 targetMissionWaypointSize = 3;</code>
     * @param value The targetMissionWaypointSize to set.
     */
    private void setTargetMissionWaypointSize(int value) {
      
      targetMissionWaypointSize_ = value;
    }
    /**
     * <pre>
     *飞机当前航线的总航点数(航线开始-结束)
     * </pre>
     *
     * <code>int32 targetMissionWaypointSize = 3;</code>
     */
    private void clearTargetMissionWaypointSize() {
      
      targetMissionWaypointSize_ = 0;
    }

    public static final int WAYPOINTV2MISSIONEXECUTESTATE_FIELD_NUMBER = 2;
    private int waypointV2MissionExecuteState_;
    /**
     * <code>.MissionExecution.WaypointV2MissionExecuteState waypointV2MissionExecuteState = 2;</code>
     * @return The enum numeric value on the wire for waypointV2MissionExecuteState.
     */
    @java.lang.Override
    public int getWaypointV2MissionExecuteStateValue() {
      return waypointV2MissionExecuteState_;
    }
    /**
     * <code>.MissionExecution.WaypointV2MissionExecuteState waypointV2MissionExecuteState = 2;</code>
     * @return The waypointV2MissionExecuteState.
     */
    @java.lang.Override
    public com.apron.mobilesdk.state.ProtoMissionExecution.MissionExecution.WaypointV2MissionExecuteState getWaypointV2MissionExecuteState() {
      com.apron.mobilesdk.state.ProtoMissionExecution.MissionExecution.WaypointV2MissionExecuteState result = com.apron.mobilesdk.state.ProtoMissionExecution.MissionExecution.WaypointV2MissionExecuteState.forNumber(waypointV2MissionExecuteState_);
      return result == null ? com.apron.mobilesdk.state.ProtoMissionExecution.MissionExecution.WaypointV2MissionExecuteState.UNRECOGNIZED : result;
    }
    /**
     * <code>.MissionExecution.WaypointV2MissionExecuteState waypointV2MissionExecuteState = 2;</code>
     * @param value The enum numeric value on the wire for waypointV2MissionExecuteState to set.
     */
    private void setWaypointV2MissionExecuteStateValue(int value) {
        waypointV2MissionExecuteState_ = value;
    }
    /**
     * <code>.MissionExecution.WaypointV2MissionExecuteState waypointV2MissionExecuteState = 2;</code>
     * @param value The waypointV2MissionExecuteState to set.
     */
    private void setWaypointV2MissionExecuteState(com.apron.mobilesdk.state.ProtoMissionExecution.MissionExecution.WaypointV2MissionExecuteState value) {
      waypointV2MissionExecuteState_ = value.getNumber();
      
    }
    /**
     * <code>.MissionExecution.WaypointV2MissionExecuteState waypointV2MissionExecuteState = 2;</code>
     */
    private void clearWaypointV2MissionExecuteState() {
      
      waypointV2MissionExecuteState_ = 0;
    }

    public static com.apron.mobilesdk.state.ProtoMissionExecution.MissionExecution parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.apron.mobilesdk.state.ProtoMissionExecution.MissionExecution parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.apron.mobilesdk.state.ProtoMissionExecution.MissionExecution parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.apron.mobilesdk.state.ProtoMissionExecution.MissionExecution parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.apron.mobilesdk.state.ProtoMissionExecution.MissionExecution parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.apron.mobilesdk.state.ProtoMissionExecution.MissionExecution parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.apron.mobilesdk.state.ProtoMissionExecution.MissionExecution parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.apron.mobilesdk.state.ProtoMissionExecution.MissionExecution parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.apron.mobilesdk.state.ProtoMissionExecution.MissionExecution parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.apron.mobilesdk.state.ProtoMissionExecution.MissionExecution parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.apron.mobilesdk.state.ProtoMissionExecution.MissionExecution parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.apron.mobilesdk.state.ProtoMissionExecution.MissionExecution parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.apron.mobilesdk.state.ProtoMissionExecution.MissionExecution prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code MissionExecution}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.apron.mobilesdk.state.ProtoMissionExecution.MissionExecution, Builder> implements
        // @@protoc_insertion_point(builder_implements:MissionExecution)
        com.apron.mobilesdk.state.ProtoMissionExecution.MissionExecutionOrBuilder {
      // Construct using com.apron.mobilesdk.state.ProtoMissionExecution.MissionExecution.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *飞机将执行的下一个任务的航路点索引。(平台取此值表示已过航点)
       * </pre>
       *
       * <code>int32 targetWaypointIndex = 1;</code>
       * @return The targetWaypointIndex.
       */
      @java.lang.Override
      public int getTargetWaypointIndex() {
        return instance.getTargetWaypointIndex();
      }
      /**
       * <pre>
       *飞机将执行的下一个任务的航路点索引。(平台取此值表示已过航点)
       * </pre>
       *
       * <code>int32 targetWaypointIndex = 1;</code>
       * @param value The targetWaypointIndex to set.
       * @return This builder for chaining.
       */
      public Builder setTargetWaypointIndex(int value) {
        copyOnWrite();
        instance.setTargetWaypointIndex(value);
        return this;
      }
      /**
       * <pre>
       *飞机将执行的下一个任务的航路点索引。(平台取此值表示已过航点)
       * </pre>
       *
       * <code>int32 targetWaypointIndex = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTargetWaypointIndex() {
        copyOnWrite();
        instance.clearTargetWaypointIndex();
        return this;
      }

      /**
       * <pre>
       *飞机当前航线的总航点数(航线开始-结束)
       * </pre>
       *
       * <code>int32 targetMissionWaypointSize = 3;</code>
       * @return The targetMissionWaypointSize.
       */
      @java.lang.Override
      public int getTargetMissionWaypointSize() {
        return instance.getTargetMissionWaypointSize();
      }
      /**
       * <pre>
       *飞机当前航线的总航点数(航线开始-结束)
       * </pre>
       *
       * <code>int32 targetMissionWaypointSize = 3;</code>
       * @param value The targetMissionWaypointSize to set.
       * @return This builder for chaining.
       */
      public Builder setTargetMissionWaypointSize(int value) {
        copyOnWrite();
        instance.setTargetMissionWaypointSize(value);
        return this;
      }
      /**
       * <pre>
       *飞机当前航线的总航点数(航线开始-结束)
       * </pre>
       *
       * <code>int32 targetMissionWaypointSize = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTargetMissionWaypointSize() {
        copyOnWrite();
        instance.clearTargetMissionWaypointSize();
        return this;
      }

      /**
       * <code>.MissionExecution.WaypointV2MissionExecuteState waypointV2MissionExecuteState = 2;</code>
       * @return The enum numeric value on the wire for waypointV2MissionExecuteState.
       */
      @java.lang.Override
      public int getWaypointV2MissionExecuteStateValue() {
        return instance.getWaypointV2MissionExecuteStateValue();
      }
      /**
       * <code>.MissionExecution.WaypointV2MissionExecuteState waypointV2MissionExecuteState = 2;</code>
       * @param value The waypointV2MissionExecuteState to set.
       * @return This builder for chaining.
       */
      public Builder setWaypointV2MissionExecuteStateValue(int value) {
        copyOnWrite();
        instance.setWaypointV2MissionExecuteStateValue(value);
        return this;
      }
      /**
       * <code>.MissionExecution.WaypointV2MissionExecuteState waypointV2MissionExecuteState = 2;</code>
       * @return The waypointV2MissionExecuteState.
       */
      @java.lang.Override
      public com.apron.mobilesdk.state.ProtoMissionExecution.MissionExecution.WaypointV2MissionExecuteState getWaypointV2MissionExecuteState() {
        return instance.getWaypointV2MissionExecuteState();
      }
      /**
       * <code>.MissionExecution.WaypointV2MissionExecuteState waypointV2MissionExecuteState = 2;</code>
       * @param value The enum numeric value on the wire for waypointV2MissionExecuteState to set.
       * @return This builder for chaining.
       */
      public Builder setWaypointV2MissionExecuteState(com.apron.mobilesdk.state.ProtoMissionExecution.MissionExecution.WaypointV2MissionExecuteState value) {
        copyOnWrite();
        instance.setWaypointV2MissionExecuteState(value);
        return this;
      }
      /**
       * <code>.MissionExecution.WaypointV2MissionExecuteState waypointV2MissionExecuteState = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearWaypointV2MissionExecuteState() {
        copyOnWrite();
        instance.clearWaypointV2MissionExecuteState();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MissionExecution)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.apron.mobilesdk.state.ProtoMissionExecution.MissionExecution();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "targetWaypointIndex_",
              "waypointV2MissionExecuteState_",
              "targetMissionWaypointSize_",
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0004\u0002\f" +
                "\u0003\u0004";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.apron.mobilesdk.state.ProtoMissionExecution.MissionExecution> parser = PARSER;
          if (parser == null) {
            synchronized (com.apron.mobilesdk.state.ProtoMissionExecution.MissionExecution.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.apron.mobilesdk.state.ProtoMissionExecution.MissionExecution>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:MissionExecution)
    private static final com.apron.mobilesdk.state.ProtoMissionExecution.MissionExecution DEFAULT_INSTANCE;
    static {
      MissionExecution defaultInstance = new MissionExecution();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        MissionExecution.class, defaultInstance);
    }

    public static com.apron.mobilesdk.state.ProtoMissionExecution.MissionExecution getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<MissionExecution> PARSER;

    public static com.google.protobuf.Parser<MissionExecution> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
